name: Go Build Tag and Release

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build-and-release:
    runs-on: [self-hosted, Linux, X64, gh_explorer]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Build MacOS binary
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -o gh_explorer

      - name: Build Windows binary
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -o gh_explorer.exe

      - name: Calculate next tag
        id: create_tag
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          DATE=$(date +'%Y%m%d')
          UNIX_TIME=$(date +%s)
          HEX_UNIX_TIME=$(printf '%x' $UNIX_TIME)
          echo "tag=v_${COMMIT_SHA}.${HEX_UNIX_TIME}" >> $GITHUB_OUTPUT
          echo "tagname=${DATE}_${COMMIT_SHA}" >> $GITHUB_OUTPUT

      - name: Create and Push Tag
        run: |
          git tag ${{ steps.create_tag.outputs.tag }} ${{ github.sha }}
          git push origin ${{ steps.create_tag.outputs.tag }}

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          release_name: ${{ steps.create_tag.outputs.tagname }}
          draft: false
          prerelease: false

      - name: Upload Release for MacOS
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gh_explorer
          asset_name: gh_explorer
          asset_content_type: application/octet-stream

      - name: Upload Release for Windows
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.FIRST_REPO_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gh_explorerexe
          asset_name: gh_explorer.exe
          asset_content_type: application/octet-stream
